apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    concurrency: 4
    useBuildkit: true
    push: false
  artifacts:
    - image: solomon_base
      context: .
      docker:
        dockerfile: tools/docker/base/Dockerfile
