apiVersion: skaffold/v2beta26
kind: Config
requires:
  - path: ./skaffold.base.yaml
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: db
      context: .
      docker:
        dockerfile: apps/db/Dockerfile
        buildArgs:
          # These vars are different per each developer and cannot be part of ConfigMap in git
          SOLOMON_DEV_NAMESPACE: '{{.SOLOMON_DEV_NAMESPACE}}'
    - image: api.dev
      context: .
      requires:
        - image: solomon_base
          alias: SOLOMON_BASE
      sync:
        manual:
          - src: 'apps/api/src/**/*'
            dest: '/usr/src'
          - src: 'libs/api/*/src/**/*'
            dest: '/usr/src'
          - src: 'libs/backend/*/src/**/*'
            dest: '/usr/src'
          - src: 'libs/shared/*/src/**/*'
            dest: '/usr/src'
      docker:
        dockerfile: apps/api/Dockerfile
        target: dev
        buildArgs:
          # These vars are different per each developer and cannot be part of ConfigMap in git
          SOLOMON_DEV_NAMESPACE: '{{.SOLOMON_DEV_NAMESPACE}}'
deploy:
  kubeContext: docker-desktop
  helm:
    releases:
      - name: postgresql
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        version: 10.12.3
        overrides:
          postgresqlPassword: 'postgres'
          initdbScripts:
            solomon-db.sql: |
              CREATE DATABASE solomon;
              GRANT ALL PRIVILEGES ON DATABASE solomon_db TO postgres;
          persistence:
            enabled: false
  kubectl:
    manifests:
      - tools/k8s/dev/api/*.yaml

portForward:
  # Expose API for E2E testing
  - resourceType: service
    resourceName: api
    port: 3000
