apiVersion: skaffold/v2beta24
kind: Config
build:
  local:
    concurrency: 4
    useBuildkit: true
    push: false
  artifacts:
    - image: solomon_base
      context: .
      docker:
        dockerfile: tools/docker/base/Dockerfile
    - image: db
      context: .
      docker:
        dockerfile: apps/db/Dockerfile
        buildArgs:
          # These vars are different per each developer and cannot be part of ConfigMap in git
          SOLOMON_DEV_NAMESPACE: '{{.SOLOMON_DEV_NAMESPACE}}'
    - image: api-dispute.dev
      context: .
      requires:
        - image: solomon_base
          alias: SOLOMON_BASE
      sync:
        manual:
          - src: 'apps/api-dispute/src/**/*'
            dest: '/usr/src'
          # - src: 'libs/api-dispute/*/src/**/*'
          #   dest: '/usr/src'
      docker:
        dockerfile: apps/api-dispute/Dockerfile
        target: dev
        buildArgs:
          # These vars are different per each developer and cannot be part of ConfigMap in git
          SOLOMON_DEV_NAMESPACE: '{{.SOLOMON_DEV_NAMESPACE}}'
    - image: api-evidence.dev
      context: .
      requires:
        - image: solomon_base
          alias: SOLOMON_BASE
      sync:
        manual:
          - src: 'apps/api-evidence/src/**/*'
            dest: '/usr/src'
          # - src: 'libs/api-evidence/*/src/**/*'
          #   dest: '/usr/src'
      docker:
        dockerfile: apps/api-evidence/Dockerfile
        target: dev
        buildArgs:
          # These vars are different per each developer and cannot be part of ConfigMap in git
          SOLOMON_DEV_NAMESPACE: '{{.SOLOMON_DEV_NAMESPACE}}'
    - image: blockchain-watcher.dev
      context: .
      requires:
        - image: solomon_base
          alias: SOLOMON_BASE
      sync:
        manual:
          - src: 'apps/blockchain-watcher/src/**/*'
            dest: '/usr/src'
          - src: 'libs/blockchain-watcher/*/src/**/*'
            dest: '/usr/src'
          - src: 'libs/shared/*/src/**/*'
            dest: '/usr/src'
      docker:
        dockerfile: apps/blockchain-watcher/Dockerfile
        target: dev
        buildArgs:
          # These vars are different per each developer and cannot be part of ConfigMap in git
          SOLOMON_DEV_NAMESPACE: '{{.SOLOMON_DEV_NAMESPACE}}'
    - image: web-evidence.dev
      context: .
      requires:
        - image: solomon_base
          alias: SOLOMON_BASE
      sync:
        manual:
          - src: 'apps/web-evidence/src/**/*'
            dest: '/usr/src'
          - src: 'libs/shared/*/src/**/*'
            dest: '/usr/src'
          - src: 'libs/web/*/src/**/*'
            dest: '/usr/src'
      docker:
        dockerfile: apps/web-evidence/Dockerfile
        target: dev
    - image: app-e2e.dev
      context: .
      sync:
        manual:
          - src: 'apps/app-e2e/src/**/*'
            dest: '/usr/src'
          - src: 'libs/shared/*/src/**/*'
            dest: '/usr/src'
      docker:
        dockerfile: apps/app-e2e/Dockerfile
        target: dev
deploy:
  kubeContext: docker-desktop
  helm:
    releases:
      - name: nginx-ingress
        repo: https://kubernetes.github.io/ingress-nginx
        remoteChart: ingress-nginx
        version: 3.34.0
        # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
        overrides:
          controller:
            admissionWebhooks:
              enabled: false
      - name: postgresql
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        version: 10.12.3
        overrides:
          postgresqlPassword: 'postgres'
          persistence:
            enabled: false
  kubectl:
    manifests:
      - tools/k8s/dev/*.yaml
portForward:
  # Enable live reload for the web app
  - resourceType: deployment
    resourceName: web-evidence
    port: 8000
  # Expose Postgres for localhost connection
  - resourceType: service
    resourceName: postgresql
    port: 5432
  # Expose API for local E2E run
  - resourceType: service
    resourceName: api-dispute
    port: 3000
  - resourceType: service
    resourceName: api-evidence
    port: 3010
  - resourceType: service
    resourceName: blockchain-watcher
    port: 4000
  - resourceType: service
    resourceName: app-e2e
    port: 8485
