/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = string
export type Party1 = string
export type Party2 = string
export type Contract = string
export type Id = string
export type Judgecontract = string
export type Awardedto = string
export type Type1 = string
export type Party11 = string
export type Party21 = string
export type Contract1 = string
export type Id1 = string
export type Judgecontract1 = string
export type Type2 = string
export type Party12 = string
export type Party22 = string
export type Contract2 = string
export type Id2 = string
export type Judgecontract2 = string
export type Evidenceurl = string
export type Submitter = string
export type Type3 = string
export type Party13 = string
export type Party23 = string
export type Contract3 = string
export type Id3 = string
export type Judgecontract3 = string
export type Token = string
export type Discount = number
export type Ethpaid = string

export interface EventSchema {}
/**
 * This interface was referenced by `EventSchema`'s JSON-Schema
 * via the `definition` "DisputeCompletedEvent".
 */
export interface DisputeCompletedEvent {
  type: Type
  party1: Party1
  party2: Party2
  contract: Contract
  id: Id
  judgeContract: Judgecontract
  awardedTo: Awardedto
}
/**
 * This interface was referenced by `EventSchema`'s JSON-Schema
 * via the `definition` "DisputeCreatedEvent".
 */
export interface DisputeCreatedEvent {
  type: Type1
  party1: Party11
  party2: Party21
  contract: Contract1
  id: Id1
  judgeContract: Judgecontract1
}
/**
 * This interface was referenced by `EventSchema`'s JSON-Schema
 * via the `definition` "EvidenceSubmittedEvent".
 */
export interface EvidenceSubmittedEvent {
  type: Type2
  party1: Party12
  party2: Party22
  contract: Contract2
  id: Id2
  judgeContract: Judgecontract2
  evidenceUrl: Evidenceurl
  submitter: Submitter
}
/**
 * This interface was referenced by `EventSchema`'s JSON-Schema
 * via the `definition` "PaymentCreatedEvent".
 */
export interface PaymentCreatedEvent {
  type: Type3
  party1: Party13
  party2: Party23
  contract: Contract3
  id: Id3
  judgeContract: Judgecontract3
  token: Token
  discount: Discount
  ethPaid: Ethpaid
}
