/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface SlmChargebackInterface extends ethers.utils.Interface {
  functions: {
    "buyer()": FunctionFragment;
    "buyerEvidenceURL()": FunctionFragment;
    "buyerWithdraw()": FunctionFragment;
    "discount()": FunctionFragment;
    "disputePeriod()": FunctionFragment;
    "disputeTime()": FunctionFragment;
    "initializeChargeback(address,address,address,address,uint8)": FunctionFragment;
    "judge()": FunctionFragment;
    "merchant()": FunctionFragment;
    "merchantEvidence(string)": FunctionFragment;
    "merchantEvidenceURL()": FunctionFragment;
    "merchantWithdraw()": FunctionFragment;
    "requestChargeback(string)": FunctionFragment;
    "state()": FunctionFragment;
    "token()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "buyer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyerEvidenceURL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyerWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "discount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "disputePeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputeTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeChargeback",
    values: [string, string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "judge", values?: undefined): string;
  encodeFunctionData(functionFragment: "merchant", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "merchantEvidence",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "merchantEvidenceURL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merchantWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestChargeback",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "buyer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "buyerEvidenceURL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "discount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputePeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputeTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeChargeback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "judge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "merchant", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merchantEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merchantEvidenceURL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "merchantWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestChargeback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "DisputeInitiated(address,address)": EventFragment;
    "Evidence(address,string)": EventFragment;
    "Funded(uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DisputeInitiated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Evidence"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Funded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type DisputeInitiatedEvent = TypedEvent<
  [string, string],
  { party1: string; party2: string }
>;

export type DisputeInitiatedEventFilter =
  TypedEventFilter<DisputeInitiatedEvent>;

export type EvidenceEvent = TypedEvent<
  [string, string],
  { party: string; evidenceURL: string }
>;

export type EvidenceEventFilter = TypedEventFilter<EvidenceEvent>;

export type FundedEvent = TypedEvent<[BigNumber], { amount: BigNumber }>;

export type FundedEventFilter = TypedEventFilter<FundedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface SlmChargeback extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SlmChargebackInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyer(overrides?: CallOverrides): Promise<[string]>;

    buyerEvidenceURL(overrides?: CallOverrides): Promise<[string]>;

    buyerWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    discount(overrides?: CallOverrides): Promise<[number]>;

    disputePeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    disputeTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    initializeChargeback(
      _judge: string,
      _token: string,
      _merchant: string,
      _buyer: string,
      _discount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    judge(overrides?: CallOverrides): Promise<[string]>;

    merchant(overrides?: CallOverrides): Promise<[string]>;

    merchantEvidence(
      _evidenceURL: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    merchantEvidenceURL(overrides?: CallOverrides): Promise<[string]>;

    merchantWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestChargeback(
      _evidenceURL: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    state(overrides?: CallOverrides): Promise<[number]>;

    token(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  buyer(overrides?: CallOverrides): Promise<string>;

  buyerEvidenceURL(overrides?: CallOverrides): Promise<string>;

  buyerWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  discount(overrides?: CallOverrides): Promise<number>;

  disputePeriod(overrides?: CallOverrides): Promise<BigNumber>;

  disputeTime(overrides?: CallOverrides): Promise<BigNumber>;

  initializeChargeback(
    _judge: string,
    _token: string,
    _merchant: string,
    _buyer: string,
    _discount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  judge(overrides?: CallOverrides): Promise<string>;

  merchant(overrides?: CallOverrides): Promise<string>;

  merchantEvidence(
    _evidenceURL: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  merchantEvidenceURL(overrides?: CallOverrides): Promise<string>;

  merchantWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestChargeback(
    _evidenceURL: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  state(overrides?: CallOverrides): Promise<number>;

  token(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyer(overrides?: CallOverrides): Promise<string>;

    buyerEvidenceURL(overrides?: CallOverrides): Promise<string>;

    buyerWithdraw(overrides?: CallOverrides): Promise<void>;

    discount(overrides?: CallOverrides): Promise<number>;

    disputePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    disputeTime(overrides?: CallOverrides): Promise<BigNumber>;

    initializeChargeback(
      _judge: string,
      _token: string,
      _merchant: string,
      _buyer: string,
      _discount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    judge(overrides?: CallOverrides): Promise<string>;

    merchant(overrides?: CallOverrides): Promise<string>;

    merchantEvidence(
      _evidenceURL: string,
      overrides?: CallOverrides
    ): Promise<void>;

    merchantEvidenceURL(overrides?: CallOverrides): Promise<string>;

    merchantWithdraw(overrides?: CallOverrides): Promise<void>;

    requestChargeback(
      _evidenceURL: string,
      overrides?: CallOverrides
    ): Promise<void>;

    state(overrides?: CallOverrides): Promise<number>;

    token(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DisputeInitiated(address,address)"(
      party1?: string | null,
      party2?: string | null
    ): DisputeInitiatedEventFilter;
    DisputeInitiated(
      party1?: string | null,
      party2?: string | null
    ): DisputeInitiatedEventFilter;

    "Evidence(address,string)"(
      party?: string | null,
      evidenceURL?: null
    ): EvidenceEventFilter;
    Evidence(party?: string | null, evidenceURL?: null): EvidenceEventFilter;

    "Funded(uint256)"(amount?: null): FundedEventFilter;
    Funded(amount?: null): FundedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    buyer(overrides?: CallOverrides): Promise<BigNumber>;

    buyerEvidenceURL(overrides?: CallOverrides): Promise<BigNumber>;

    buyerWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    discount(overrides?: CallOverrides): Promise<BigNumber>;

    disputePeriod(overrides?: CallOverrides): Promise<BigNumber>;

    disputeTime(overrides?: CallOverrides): Promise<BigNumber>;

    initializeChargeback(
      _judge: string,
      _token: string,
      _merchant: string,
      _buyer: string,
      _discount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    judge(overrides?: CallOverrides): Promise<BigNumber>;

    merchant(overrides?: CallOverrides): Promise<BigNumber>;

    merchantEvidence(
      _evidenceURL: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    merchantEvidenceURL(overrides?: CallOverrides): Promise<BigNumber>;

    merchantWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestChargeback(
      _evidenceURL: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    state(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyerEvidenceURL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyerWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    discount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    disputePeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    disputeTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initializeChargeback(
      _judge: string,
      _token: string,
      _merchant: string,
      _buyer: string,
      _discount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    judge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    merchant(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    merchantEvidence(
      _evidenceURL: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    merchantEvidenceURL(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    merchantWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestChargeback(
      _evidenceURL: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    state(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
