#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^[a-z0-9_-]+$"

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "Invalid branch name. Branch names must match: $valid_branch_regex . Please rename the branch and try again."
    exit 1
fi

exit 0

pnpx pretty-quick --staged
