name: CI

on:
  pull_request:
    branches: [main]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - run: pnpm install
      - run: pnpm test
      - run: pnpx semantic-release
